ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  python: 3.10

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
    #- repo: https://github.com/pre-commit/mirrors-prettier
    #rev: "v3.0.3"
    #    hooks:
    #  - id: prettier
    #    types_or: [yaml, markdown, html, css, scss, javascript, json]
    #    args: [--prose-wrap=always]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.7.1'  # Use the sha / tag you want to point at
#    hooks:
#      -  id: mypy
#         args: [--ignore-missing-imports]
#         additional_dependencies: ['types-PyYAML']
