#### Data parameters

datapath: tests/testdata_npy
affinity: tests/testdata_npy/affinity_an.csv
classes: tests/testdata_npy/classes.csv
restart: False
limit: 1000
split: 20
datatype: npy

#### Data processing parameters
shift_mean: False
gaussian_blur: False
normalise: False
rescale: False

#### Network parameters

depth:  3
channels:  64
latent_dims:  8
pose_dims: 1
model: a

#### Training parameters

no_val_drop: true
epochs:  1000
batch:  128
learning:  0.001
gpu:  true
freq_sta: 10  # frequency of state saves

#### Loss parameters

beta:  1
gamma:  2
loss_fn:  MSE

#### Cyclical annealing parameters for beta
beta_min: 0
beta_cycle: 5
beta_ratio: 0.5
cyc_method_beta :  cycle_sigmoid

#### Cyclical annealing parameters for gamma
gamma_min: 0
gamma_cycle: 5
gamma_ratio: 0.5
cyc_method_gamma :  cycle_sigmoid

#### Evaluation parameters
eval:  false
freq_eval: 10 # frequency of test evaluation (if test present)

#### Visualization parameters
vis_los:  false  # loss on/off (every epoch from epoch 2)
vis_acc:  false  # confusion matrices and F1 scores on/off (frequency controlled)
vis_rec:  false  # reconstructions on/off (frequency controlled)
vis_emb:  false  # latent embeddings on/off (frequency controlled)
vis_int:  false  # latent interpolations on/off (frequency controlled)
vis_dis:  false  # latent disentanglement on/off (frequency controlled)
vis_pos:  false  # pose disentanglement on/off (frequency controlled)
vis_pose_class: 1,2 # comma separated string eg. 1,2
vis_cyc:  false  # beta for cyclic anealing on/off (once per run)
vis_aff: false   # affinity matrix on/off (once per run)
vis_his:  false  # class distribution histogram on/off (once per run)
vis_sim:  false  # latent space similarity matrix on/off
vis_all:  true   # sets all above to on/off
dynamic: true    # dynamic embedding visualisations on/off (freq same as freq_emb)

freq_acc: 10  # frequency of accuracy visualisation
freq_rec: 10  # frequency of reconstruction visualisation
freq_emb: 10  # frequency of latent embedding visualisation
freq_int: 10  # frequency of latent interpolation visualisation
freq_dis: 10  # frequency of latent disentanglement visualisation
freq_pos: 10  # frequency of pose disentanglement visualisation
freq_sim: 10  # frequency of similarity matrix visualisation
freq_all: 10  # sets all above to the same value (inc freq_sta and freq_eval)

#### debug parameters
debug: false
