##################################
# This input file contains the parameters required for running
# run_create_subtomo.py
# This run script can preprocess a full tomogram by applying various filters such as :
#  Normalisation
#  add gaussian noise for benchmarking purposes
#  apply a bandpass filter fiven a low and high frequency threshold
#  create augmentations of the voxel where the voxels are rotated between a minimum and maximum input angle
#  can apply padding
#  Not implemented yet : can apply crop after rotation
#  Not Implemented yet: gaussian blur

#### Data parameters
input_path: /Users/mfamili/work/test_affinity_merge/test_create_subtomo_avae
annot_path: /Users/mfamili/work/test_affinity_merge/test_create_subtomo_avae
output_path: /Users/mfamili/work/test_affinity_merge/test_create_subtomo_avae/subtomos

####
datatype: mrc
vox_size: [32, 32, 32]

### Filters
bandpass: False
low_freq: 0
high_freq: 15
gaussian_blur: True
normalise: True
add_noise: True
noise_int: 3

#### augmentation
augment: 3
aug_th_min: -20
aug_th_max: 20
